### ISSUE TITLE
font size settings and U+279c character missing

### ISSUE THREAD

**Issue by peleusj** [delphinus/homebrew-sfmono-square#95]
Thanks for making this great font that take care of Japanese and nerd font, but I have some confusion in using this great font, I am using Kitty and Iterm2, both have these problems:
1. U+279c, right arrow symbol, part of robbyrussell zsh prompt, seems not include?
2. The size of this font need to be set much bigger than normal font to get same visual size, is there something I'm missing?

**Comment by delphinus** [comment]
> 1. U+279c, right arrow symbol, part of robbyrussell zsh prompt, seems not include?

U+279C does not exist on both SF Mono and Migu1M. So neither SF Mono Square does.

You should use → (U+2192) or glyphs in nerdfonts. You can find them [here](https://www.nerdfonts.com/cheat-sheet) with searching `arrow_right`, for example.

> 2. The size of this font need to be set much bigger than normal font to get same visual size, is there something I'm missing?

This is because the aspect ratio of the original glyphs differ, SF Mono and Migu1M.

| SF Mono | Migu1M |
|---|---|
| <img width="285" src="https://github.com/delphinus/homebrew-sfmono-square/assets/1239245/2e2f3022-801b-432f-a0ae-ea5065b52a79"> | <img width="289" src="https://github.com/delphinus/homebrew-sfmono-square/assets/1239245/f3360607-4168-413e-b746-036cb3232f82">

The script in this formula reduces the size of glyphs from SF Mono, and combinate with glyphs from Migu1M. I wrote more detail logic in this article: [The story of making the best programming font with SF Mono][]. This is written in Japanese, so you can use Google Translation to read.

**Comment by delphinus** [comment]
> 1. U+279c, right arrow symbol, part of robbyrussell zsh prompt, seems not include?

U+279C does not exist on both SF Mono and Migu1M. So neither SF Mono Square does.

You should use → (U+2192) or glyphs in nerdfonts. You can find them [here](https://www.nerdfonts.com/cheat-sheet) with searching `arrow_right`, for example.

> 2. The size of this font need to be set much bigger than normal font to get same visual size, is there something I'm missing?

This is because the aspect ratio of the original glyphs differ, SF Mono and Migu1M.

| SF Mono | Migu1M |
|---|---|
| <img width="285" src="https://github.com/delphinus/homebrew-sfmono-square/assets/1239245/2e2f3022-801b-432f-a0ae-ea5065b52a79"> | <img width="289" src="https://github.com/delphinus/homebrew-sfmono-square/assets/1239245/f3360607-4168-413e-b746-036cb3232f82">

The script in this formula reduces the size of glyphs from SF Mono, and combinate with glyphs from Migu1M. I wrote more detail logic in this article: [The story of making the best programming font with SF Mono][]. This is written in Japanese, so you can use Google Translation to read.

**Comment by peleusj** [comment]
Sorry for the delayed response. Thank you for your detailed explanation. 
I don't have any more questions, and once again, thank you for this awesome font.
